"""
crm-billing-bridge

An OpenAI-compatible HTTP proxy that sits between mostakinads-design/crm-laravel
(Liberu CRM) and LocalAI, enabling AI-powered billing invoice auto-generation.

Every AI request is:
  1. Recorded as a tracked task (GET /tasks / GET /tasks/<id>)
  2. Forwarded to the LocalAI API
  3. The generated invoice data is stored back on the task record

Endpoints
---------
  POST /v1/chat/completions   OpenAI-compatible proxy (standard AI calls from CRM)
  POST /invoices/generate     Structured invoice generation: accepts deal/contact JSON,
                              returns a ready-to-use invoice object (line items, totals,
                              payment terms, notes) generated by LocalAI
  GET  /health                Health check
  GET  /tasks                 List all tracked generation tasks
  GET  /tasks/<id>            Single task detail
  POST /tasks/update          Manually create / advance a task
  GET  /config                View current config
  POST /config/reload         Hot-reload config.json without restarting
"""
import http.client
import json
import os
import sys
import threading
import urllib.parse
import uuid
from http.server import BaseHTTPRequestHandler, HTTPServer

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.json")

_config_lock = threading.Lock()
_config: dict = {}

_tasks_lock = threading.Lock()
_tasks: dict = {}


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------

def load_config():
    global _config
    try:
        with open(CONFIG_PATH) as f:
            data = json.load(f)
        with _config_lock:
            _config = data
        print(f"[config] loaded from {CONFIG_PATH}")
    except FileNotFoundError:
        print(f"[config] {CONFIG_PATH} not found, using defaults")
    except json.JSONDecodeError as e:
        print(f"[config] parse error: {e}")


def get_config() -> dict:
    with _config_lock:
        return dict(_config)


# ---------------------------------------------------------------------------
# Task registry helpers
# ---------------------------------------------------------------------------

def upsert_task(task_id: str, updates: dict) -> dict:
    with _tasks_lock:
        if task_id in _tasks:
            _tasks[task_id].update(updates)
            _tasks[task_id]["task_id"] = task_id
        else:
            _tasks[task_id] = {"task_id": task_id, "status": "pending", **updates}
        return dict(_tasks[task_id])


def get_task(task_id: str):
    with _tasks_lock:
        return _tasks.get(task_id)


def list_tasks() -> list:
    with _tasks_lock:
        return list(_tasks.values())


# ---------------------------------------------------------------------------
# LocalAI proxy helper
# ---------------------------------------------------------------------------

def call_localai(payload: dict) -> tuple:
    """POST a chat completion payload to LocalAI.

    Returns (http_status: int, response_body: bytes).
    """
    cfg = get_config()
    localai_url = cfg.get("localai_base_url", "http://api:8080/v1")
    parsed = urllib.parse.urlparse(localai_url)
    host = parsed.hostname
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    base_path = parsed.path.rstrip("/")
    path = base_path + "/chat/completions"

    body_bytes = json.dumps(payload).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "Content-Length": str(len(body_bytes)),
    }

    conn = http.client.HTTPConnection(host, port, timeout=180)
    conn.request("POST", path, body=body_bytes, headers=headers)
    resp = conn.getresponse()
    resp_body = resp.read()
    conn.close()
    return resp.status, resp_body


def proxy_raw(path: str, body_bytes: bytes, request_headers) -> tuple:
    """Forward an arbitrary POST to LocalAI, return (status, resp_headers, body)."""
    cfg = get_config()
    localai_url = cfg.get("localai_base_url", "http://api:8080/v1")
    parsed = urllib.parse.urlparse(localai_url)
    host = parsed.hostname
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    base_path = parsed.path.rstrip("/")
    forward_path = base_path + path[len("/v1"):]

    headers = {
        "Content-Type": request_headers.get("Content-Type", "application/json"),
        "Content-Length": str(len(body_bytes)),
        "Authorization": request_headers.get("Authorization", ""),
    }

    conn = http.client.HTTPConnection(host, port, timeout=180)
    conn.request("POST", forward_path, body=body_bytes, headers=headers)
    resp = conn.getresponse()
    resp_body = resp.read()
    resp_headers = dict(resp.getheaders())
    conn.close()
    return resp.status, resp_headers, resp_body


# ---------------------------------------------------------------------------
# Invoice generation logic
# ---------------------------------------------------------------------------

INVOICE_SYSTEM_PROMPT = """You are a professional billing assistant for a CRM system.
When given customer and deal data, you generate a complete, ready-to-use invoice as
structured JSON. Your output MUST be valid JSON and nothing else — no markdown fences,
no explanations. Use this exact schema:

{
  "invoice_number": "<suggested invoice number, e.g. INV-2024-0001>",
  "issue_date": "<YYYY-MM-DD>",
  "due_date": "<YYYY-MM-DD, typically 30 days after issue>",
  "currency": "<3-letter ISO code, default USD>",
  "client": {
    "name": "<customer name>",
    "email": "<customer email if provided>",
    "address": "<address if provided>"
  },
  "line_items": [
    {
      "description": "<item description>",
      "quantity": <number>,
      "unit_price": <number>,
      "total": <number>
    }
  ],
  "subtotal": <number>,
  "tax_rate": <percentage as decimal e.g. 0.1 for 10%>,
  "tax_amount": <number>,
  "total": <number>,
  "payment_terms": "<e.g. Net 30>",
  "notes": "<any relevant notes or instructions>"
}"""

INVOICE_USER_TEMPLATE = """Generate a billing invoice for the following CRM deal:

Customer: {customer_name}
Email: {customer_email}
Company: {company}
Deal: {deal_title}
Deal Value: {deal_value} {currency}
Products/Services: {products}
Notes: {notes}

Today's date: {today}

Return only the JSON invoice object."""


def build_invoice_prompt(data: dict) -> list:
    """Build the messages list for an invoice generation request."""
    user_content = INVOICE_USER_TEMPLATE.format(
        customer_name=data.get("customer_name", "N/A"),
        customer_email=data.get("customer_email", "N/A"),
        company=data.get("company", "N/A"),
        deal_title=data.get("deal_title", data.get("title", "N/A")),
        deal_value=data.get("deal_value", data.get("amount", "N/A")),
        currency=data.get("currency", "USD"),
        products=data.get("products", data.get("line_items", "Based on deal")),
        notes=data.get("notes", ""),
        today=data.get("today", __import__("datetime").date.today().isoformat()),
    )
    return [
        {"role": "system", "content": INVOICE_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def extract_json_from_text(text: str):
    """Try to parse JSON from a model response that may contain prose."""
    text = text.strip()
    # Strip markdown code fences if present
    if text.startswith("```"):
        lines = text.splitlines()
        text = "\n".join(
            line for line in lines
            if not line.strip().startswith("```")
        ).strip()
    try:
        return json.loads(text), None
    except json.JSONDecodeError as e:
        return None, str(e)


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------

class Handler(BaseHTTPRequestHandler):

    def send_json_response(self, payload, status=200):
        body = json.dumps(payload, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def read_body(self) -> bytes:
        length = int(self.headers.get("Content-Length", 0))
        return self.rfile.read(length) if length else b"{}"

    # ------------------------------------------------------------------
    # GET
    # ------------------------------------------------------------------

    def do_GET(self):
        if self.path == "/health":
            self.send_json_response({
                "status": "ok",
                "service": "crm-billing-bridge",
                "capabilities": ["invoice-generation", "chat-completions", "task-tracking"],
            })
            return

        if self.path == "/tasks":
            self.send_json_response({"tasks": list_tasks()})
            return

        if self.path.startswith("/tasks/"):
            task_id = self.path[len("/tasks/"):]
            task = get_task(task_id)
            if task is None:
                self.send_json_response({"error": "task not found"}, status=404)
            else:
                self.send_json_response(task)
            return

        if self.path == "/config":
            self.send_json_response(get_config())
            return

        self.send_json_response({"error": "not found"}, status=404)

    # ------------------------------------------------------------------
    # POST
    # ------------------------------------------------------------------

    def do_POST(self):
        body = self.read_body()

        # ---- Structured invoice generation --------------------------------
        if self.path == "/invoices/generate":
            try:
                data = json.loads(body)
            except json.JSONDecodeError:
                self.send_json_response({"error": "invalid json body"}, status=400)
                return

            cfg = get_config()
            model = cfg.get("override_model", cfg.get("default_model", "qwen3"))

            task_id = str(uuid.uuid4())
            task = upsert_task(task_id, {
                "status": "running",
                "type": "invoice-generation",
                "model": model,
                "customer": data.get("customer_name", "unknown"),
                "deal": data.get("deal_title", data.get("title", "unknown")),
                "source": "crm-billing",
            })
            print(f"[task] {task_id} invoice-generation | customer={task['customer']} deal={task['deal']}")

            messages = build_invoice_prompt(data)
            # Allow config to override the system prompt
            system_override = cfg.get("invoice_system_prompt")
            if system_override:
                messages[0]["content"] = system_override

            payload = {"model": model, "messages": messages, "temperature": 0.3}

            try:
                status, resp_body = call_localai(payload)
            except Exception as exc:
                upsert_task(task_id, {"status": "error", "error": str(exc)})
                print(f"[task] {task_id} error: {exc}")
                self.send_json_response({"error": str(exc), "task_id": task_id}, status=502)
                return

            raw_text = ""
            try:
                parsed_resp = json.loads(resp_body)
                choices = parsed_resp.get("choices", [])
                if choices:
                    raw_text = choices[0].get("message", {}).get("content", "")
            except Exception:
                pass

            invoice_obj, parse_err = extract_json_from_text(raw_text)

            if invoice_obj:
                upsert_task(task_id, {
                    "status": "done",
                    "invoice_number": invoice_obj.get("invoice_number", ""),
                    "invoice_total": invoice_obj.get("total", ""),
                    "localai_http_status": status,
                })
                print(f"[task] {task_id} done | invoice={invoice_obj.get('invoice_number','?')} total={invoice_obj.get('total','?')}")
                self.send_json_response({"task_id": task_id, "invoice": invoice_obj})
            else:
                upsert_task(task_id, {
                    "status": "error",
                    "error": f"JSON parse failed: {parse_err}",
                    "raw_output": raw_text[:500],
                    "localai_http_status": status,
                })
                print(f"[task] {task_id} error (json parse) | {parse_err}")
                self.send_json_response({
                    "error": "invoice JSON could not be parsed from model output",
                    "parse_error": parse_err,
                    "raw_output": raw_text,
                    "task_id": task_id,
                }, status=422)
            return

        # ---- OpenAI-compatible chat completions proxy -------------------
        if self.path == "/v1/chat/completions":
            try:
                payload = json.loads(body)
            except json.JSONDecodeError:
                self.send_json_response({"error": "invalid json"}, status=400)
                return

            messages = payload.get("messages", [])
            last_user_msg = next(
                (m.get("content", "") for m in reversed(messages) if m.get("role") == "user"),
                "",
            )
            cfg = get_config()
            model = payload.get("model", cfg.get("default_model", "qwen3"))

            task_id = str(uuid.uuid4())
            upsert_task(task_id, {
                "status": "running",
                "type": "chat-completion",
                "model": model,
                "prompt_preview": last_user_msg[:200],
                "source": "crm-billing",
            })
            print(f"[task] {task_id} chat | model={model}")

            if cfg.get("override_model"):
                payload["model"] = cfg["override_model"]
                body = json.dumps(payload).encode("utf-8")

            try:
                status, resp_headers, resp_body = proxy_raw("/v1/chat/completions", body, self.headers)
            except Exception as exc:
                upsert_task(task_id, {"status": "error", "error": str(exc)})
                self.send_json_response({"error": str(exc)}, status=502)
                return

            result_text = ""
            try:
                pr = json.loads(resp_body)
                choices = pr.get("choices", [])
                if choices:
                    result_text = choices[0].get("message", {}).get("content", "")
            except Exception:
                pass

            upsert_task(task_id, {
                "status": "done" if status < 400 else "error",
                "result_preview": result_text[:300],
                "localai_http_status": status,
            })
            print(f"[task] {task_id} {'done' if status < 400 else 'error'} | http={status}")

            self.send_response(status)
            for hdr_name, hdr_val in resp_headers.items():
                if hdr_name.lower() not in ("transfer-encoding", "connection"):
                    self.send_header(hdr_name, hdr_val)
            self.send_header("Content-Length", str(len(resp_body)))
            self.end_headers()
            self.wfile.write(resp_body)
            return

        # ---- Manual task upsert -----------------------------------------
        if self.path == "/tasks/update":
            try:
                data = json.loads(body)
            except json.JSONDecodeError:
                self.send_json_response({"error": "invalid json"}, status=400)
                return
            task_id = data.get("task_id") or str(uuid.uuid4())
            task = upsert_task(task_id, data)
            print(f"[task] {task_id} -> {task.get('status')}")
            self.send_json_response({"accepted": True, "task": task})
            return

        # ---- Config reload -----------------------------------------------
        if self.path == "/config/reload":
            load_config()
            self.send_json_response({"reloaded": True, "config": get_config()})
            return

        self.send_json_response({"error": "not found"}, status=404)

    def log_message(self, fmt, *args):
        pass  # suppress noisy per-request access logs


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    load_config()
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8013
    server = HTTPServer(("0.0.0.0", port), Handler)
    print(f"crm-billing-bridge listening on {port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.server_close()
